# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 13bba71d4f08f1f20fb098047df0bbbeec7a29fbafd84568448d6cd5085d3386db68aea98af95731f3aebe20455d2fe2a9ec69aa7dc63fa7328bb14bff8eefb7

test:
  secret_key_base: 5042cc32564421d09f41b83b53db150610526afbe13bb360d0f273eb848a6a69e977c56867f20a41333d002fa911ef4fd7917683a5db872cf37a79fec5ce90d7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
